[package]
name = "daedalus"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
calypso-cangen = { path = "../calypso-cangen" }
proc-macro2.workspace = true 
quote.workspace = true 
serde_json.workspace = true 
