[package]
name = "Ner_Processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketcan = "2.0.0"

[[bin]]
name = "Ner_Processing"
path = "main.rs"
