[package]
name = "calypso"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"
default-run = "calypso"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketcan = "3.3.0"
paho-mqtt = "0.12.5"
protobuf-codegen = "3.5.1"
protobuf = "3.5.1"
bitstream-io = "2.5.3"
clap = { version = "4.5.18", features = ["derive", "env"] }
rand = "0.8"


[build-dependencies]
protobuf-codegen = "3.5.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
