[package]
name = "calypso"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"
default-run = "calypso"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["libs/daedalus", "libs/calypso-cangen"]

[workspace.dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"


[dependencies]
socketcan = "3.3.1"
paho-mqtt = "0.12.5"
protobuf-codegen = "3.5.1"
protobuf = "3.5.1"
bitstream-io = "2.6.0"
clap = { version = "4.5.20", features = ["derive", "env"] }
rand = "0.8"
phf = { version = "0.11.2", features = ["macros"] }
calypso-cangen = { path = "./libs/calypso-cangen" }
daedalus = { path = "./libs/daedalus" }


[build-dependencies]
protobuf-codegen = "3.5.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
