[workspace]
members = ["daedalus", "calypso-cangen", "calypso-simulate", "calypso"]
default-members = ["calypso"]
resolver = "2"

[workspace.dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
paho-mqtt = "0.12.5"
clap = { version = "4.5.23", features = ["derive", "env"] }
protobuf-codegen = "3.5.1"
protobuf = "3.5.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"