[package]
name = "calypso"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketcan = "3.3.0"
paho-mqtt = "0.12.5"
protobuf-codegen = "3.3.0"
protobuf = "3.3.0"
bitstream-io = "2.5.0"


[build-dependencies]
protobuf-codegen = "3.3.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
