[package]
name = "calypso-cangen"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = "2.0.18"
schemars = { workspace = true }
serde_path_to_error = "0.1.20"
definition-rs.workspace = true
