// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `src/proto/serverdata.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

// @@protoc_insertion_point(message:serverdata.v1.ServerData)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ServerData {
    // message fields
    // @@protoc_insertion_point(field:serverdata.v1.ServerData.value)
    pub value: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:serverdata.v1.ServerData.unit)
    pub unit: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:serverdata.v1.ServerData.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ServerData {
    fn default() -> &'a ServerData {
        <ServerData as ::protobuf::Message>::default_instance()
    }
}

impl ServerData {
    pub fn new() -> ServerData {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "value",
            |m: &ServerData| { &m.value },
            |m: &mut ServerData| { &mut m.value },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "unit",
            |m: &ServerData| { &m.unit },
            |m: &mut ServerData| { &mut m.unit },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ServerData>(
            "ServerData",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ServerData {
    const NAME: &'static str = "ServerData";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.value.push(is.read_string()?);
                },
                18 => {
                    self.unit = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.value {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if !self.unit.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.unit);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.value {
            os.write_string(1, &v)?;
        };
        if !self.unit.is_empty() {
            os.write_string(2, &self.unit)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ServerData {
        ServerData::new()
    }

    fn clear(&mut self) {
        self.value.clear();
        self.unit.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ServerData {
        static instance: ServerData = ServerData {
            value: ::std::vec::Vec::new(),
            unit: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ServerData {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ServerData").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ServerData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ServerData {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1asrc/proto/serverdata.proto\x12\rserverdata.v1\"6\n\nServerData\x12\
    \x14\n\x05value\x18\x01\x20\x03(\tR\x05value\x12\x12\n\x04unit\x18\x02\
    \x20\x01(\tR\x04unitJ\xb0\x01\n\x06\x12\x04\0\0\x07\x01\n\x08\n\x01\x0c\
    \x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x16\n\n\n\x02\x04\0\x12\
    \x04\x04\0\x07\x01\n\n\n\x03\x04\0\x01\x12\x03\x04\x08\x12\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03\x05\x03\x1d\n\x0c\n\x05\x04\0\x02\0\x04\x12\x03\x05\
    \x03\x0b\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x05\x0c\x12\n\x0c\n\x05\x04\
    \0\x02\0\x01\x12\x03\x05\x13\x18\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\
    \x1b\x1c\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x06\x03\x13\n\x0c\n\x05\x04\0\
    \x02\x01\x05\x12\x03\x06\x03\t\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x06\
    \n\x0e\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x06\x11\x12b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ServerData::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
